name: networkunit_env
channels:
  - damianavila82
  - defaults
dependencies:
  - rise
  - pip
  - pip:
    - jupyter==1.0.0
    - ipywidgets==7.4.2
    - ipympl==0.2.1
    - tabulate==0.8.2
    - networkx==2.2
    - seaborn==0.9.0
    - pyyaml==3.13
    - cython==0.29
    - numpy==1.15.4
    - scipy==1.2.1
    - elephant==0.6.2
    - gitpython==2.1.11
    - neo==0.7.1
    - sciunit==0.2.1
    - rdflib==4.2.2
    - odml==1.4.2.1
    - git+git://github.com/INM-6/NetworkUnit.git
